[package]
name = "image-cmp-tool"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
exr = "1.4"
structopt = "0.3"
rayon = "1.5"
lazy-regex = "2.3"